<a href="https://colab.research.google.com/github/SrushthiSb/Large-Language-Models/blob/main/LLM(Basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
llm=AutoModelForCausalLM.from_pretrained('facebook/opt-125m')
tok=AutoTokenizer.from_pretrained('facebook/opt-125m')


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/651 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/251M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.decoder.embed_tokens.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning


generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/251M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/685 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/441 [00:00<?, ?B/s]

In [ ]:
model_inputs = tok(["A list of colors"], return_tensors="pt")
generate_ids=llm.generate(**model_inputs, max_new_tokens=5)
text=tok.batch_decode(generate_ids, skip_special_tokens=True)[0]
print(text)

A list of colors and patterns for the color


In [ ]:
model_inputs.input_ids

tensor([[   2,  250,  889,    9, 8089]])

In [ ]:
generate_ids

tensor([[   2,  250,  889,    9, 8089,    8, 8117,   13,    5, 3195]])

In [ ]:
inputs_ids = model_inputs.input_ids
outputs=llm(inputs_ids)
outputs

CausalLMOutputWithPast(loss=None, logits=tensor([[[-3.4551, -3.4531, 13.1562,  ..., -3.5098, -3.5254, -3.7480],
         [-5.5898, -5.5781, -1.3184,  ..., -5.5703, -5.6211, -5.4805],
         [-6.7109, -6.7109,  0.8105,  ..., -6.6797, -6.7031, -6.8945],
         [-8.3281, -8.3203, -3.5508,  ..., -8.3438, -8.4062, -8.3359],
         [-6.9570, -6.9492,  2.0547,  ..., -7.0352, -6.7578, -7.1914]]],
       dtype=torch.float16, grad_fn=<UnsafeViewBackward0>), past_key_values=DynamicCache(layers=[DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer]), hidden_states=None, attentions=None)

In [ ]:
output=outputs.logits[:,-1].argmax()
output

tensor(8)

In [ ]:
output=outputs.logits[:,-1].argmax()
output_tok=tok.decode(output)
output_tok

' and'

In [ ]:
import torch
output_ids = model_inputs.input_ids[0].tolist()
output_ids

[2, 250, 889, 9, 8089]

In [ ]:
import torch
output_ids = model_inputs.input_ids[0].tolist()
for i in range(6):
  inputs = torch.tensor([output_ids], dtype=torch.long)
  outputs = llm(inputs)
  output_id = outputs.logits[:, -1].argmax()
  output_ids.append(output_id)
print(tok.decode(output_ids, skip_special_tokens=True))

A list of colors and patterns for the color of


In [ ]:
%pip install gensim nltk

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 75.5 MB/s eta 0:00:00


[nltk_data] Downloading package word2vec_sample to /root/nltk_data...
[nltk_data]   Unzipping models/word2vec_sample.zip.


True

In [ ]:
import gensim
import nltk
import numpy as np
nltk.download('word2vec_sample')

[nltk_data] Downloading package word2vec_sample to /root/nltk_data...
[nltk_data]   Package word2vec_sample is already up-to-date!


True

In [ ]:
word2vec_sample = str(nltk.data.find('models/word2vec_sample/pruned.word2vec.txt'))
model = gensim.models.KeyedVectors.load_word2vec_format(word2vec_sample,binary=False)

In [ ]:
king = model['king']
king[:10]

array([ 0.0434064 ,  0.0102628 ,  0.00296526,  0.0481172 , -0.00883269,
       -0.0124499 ,  0.0385274 , -0.0683062 ,  0.0176654 ,  0.125172  ],
      dtype=float32)

In [ ]:
man = model['man']
women = model['women']

In [ ]:
answer= king - man + women

In [ ]:
similarites = model.vectors.dot(answer)
indices = np.argsort(-similarites, axis=0)

for index in indices[:3]:
  word = model.index_to_key[index]
  if word not in ['king', 'man', 'women']:
    print(word)
    break

queen


In [ ]:
model.most_similar(positive=['king','women'], negative=['man'],topn=1)

[('queen', 0.48273277282714844)]

In [ ]:
model.most_similar(positive=['India','Paris'], negative=['Germany'],topn=1) #india-germany+paris

[('Delhi', 0.5633739233016968)]

In [ ]:
model.most_similar(positive=['cat','tree'], negative=['bird'],topn=2)#cat-bird+tree

[('trees', 0.5032581686973572), ('kitten', 0.49042296409606934)]

In [ ]:
orange = model['orange']
apple = model['apple']
dog = model['dog']

In [ ]:
orange.dot(apple) #higher

np.float32(0.39203453)

In [ ]:
orange.dot(dog) #low

np.float32(0.11858465)

In [ ]:
apple.dot(dog) #low

np.float32(0.21969748)